image:
  file: .gitpod.dockerfile

# ports:
#   - port: 3000
#     onOpen: ignore
#   - port: 6379
#     onOpen: ignore
#   - port: 8000
#     onOpen: ignore

tasks:
  - command: cd /workspace/frappe_codespace/.script/ && docker-compose up
  - command: cd /workspace/frappe_codespace/.script/ && bash init.sh
